//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace Lab06
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CookeryModelContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CookeryModelContainer object using the connection string found in the 'CookeryModelContainer' section of the application configuration file.
        /// </summary>
        public CookeryModelContainer() : base("name=CookeryModelContainer", "CookeryModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CookeryModelContainer object.
        /// </summary>
        public CookeryModelContainer(string connectionString) : base(connectionString, "CookeryModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CookeryModelContainer object.
        /// </summary>
        public CookeryModelContainer(EntityConnection connection) : base(connection, "CookeryModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Dish> Dishes
        {
            get
            {
                if ((_Dishes == null))
                {
                    _Dishes = base.CreateObjectSet<Dish>("Dishes");
                }
                return _Dishes;
            }
        }
        private ObjectSet<Dish> _Dishes;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Dishes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDishes(Dish dish)
        {
            base.AddObject("Dishes", dish);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CookeryModel", Name="Dish")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Dish : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Dish object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="ingridients">Initial value of the Ingridients property.</param>
        /// <param name="price">Initial value of the Price property.</param>
        /// <param name="isBought">Initial value of the IsBought property.</param>
        public static Dish CreateDish(global::System.Int32 id, global::System.String name, global::System.String ingridients, global::System.Double price, global::System.Boolean isBought)
        {
            Dish dish = new Dish();
            dish.Id = id;
            dish.Name = name;
            dish.Ingridients = ingridients;
            dish.Price = price;
            dish.IsBought = isBought;
            return dish;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Ingridients
        {
            get
            {
                return _Ingridients;
            }
            set
            {
                OnIngridientsChanging(value);
                ReportPropertyChanging("Ingridients");
                _Ingridients = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Ingridients");
                OnIngridientsChanged();
            }
        }
        private global::System.String _Ingridients;
        partial void OnIngridientsChanging(global::System.String value);
        partial void OnIngridientsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Price
        {
            get
            {
                return _Price;
            }
            set
            {
                OnPriceChanging(value);
                ReportPropertyChanging("Price");
                _Price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Price");
                OnPriceChanged();
            }
        }
        private global::System.Double _Price;
        partial void OnPriceChanging(global::System.Double value);
        partial void OnPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsBought
        {
            get
            {
                return _IsBought;
            }
            set
            {
                OnIsBoughtChanging(value);
                ReportPropertyChanging("IsBought");
                _IsBought = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsBought");
                OnIsBoughtChanged();
            }
        }
        private global::System.Boolean _IsBought;
        partial void OnIsBoughtChanging(global::System.Boolean value);
        partial void OnIsBoughtChanged();

        #endregion
    
    }

    #endregion
    
}
